version: "3.8"
services:
    web:
      container_name: web
      build: .
      ports:
          - "8080:80"
      environment:
        ASPNETCORE_ENVIRONMENT: Production
      depends_on:
        - db
    db:
        container_name: sql-server-db
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "Hartienalodka1!"
            ACCEPT_EULA: "Y"